/- Aggregate compile target for the thirteen verification modules. -/
import PrimalitySheafVerification.Spt1
import PrimalitySheafVerification.Spt2
import PrimalitySheafVerification.Spt3
import PrimalitySheafVerification.Spt4
import PrimalitySheafVerification.Spt5
import PrimalitySheafVerification.Spt6
import PrimalitySheafVerification.Spt7
import PrimalitySheafVerification.Mock1
import PrimalitySheafVerification.Mock1_Advanced
import PrimalitySheafVerification.Mock2
import PrimalitySheafVerification.Mock2_Advanced
import PrimalitySheafVerification.Mock2_FunctionalAnalysis
import PrimalitySheafVerification.QYM
