#!/usr/bin/env bash
set -euo pipefail
VARIANT=${1:?variant required}; export VARIANT
TARGET='PrimalitySheafVerification/Mock2_FunctionalAnalysis.lean'; OUT="build-logs/fa432-whole-cast/${VARIANT}"; export OUT
rm -rf "$OUT"; mkdir -p "$OUT" .lake/build/lib/lean/PrimalitySheafVerification
python3 scripts/fa432_apply_whole_prop_cast.py "$VARIANT" | tee "$OUT/apply.log"
curl --retry 5 --retry-all-errors --fail --silent --show-error https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -o /tmp/elan-init.sh
sh /tmp/elan-init.sh -y --default-toolchain none; export PATH="${HOME}/.elan/bin:${PATH}"; elan toolchain install "$(cat lean-toolchain)"; lean --version | tee "$OUT/lean-version.txt"; lake --version | tee "$OUT/lake-version.txt"; lake exe cache get | tee "$OUT/cache-get.log"; cp "$TARGET" "$OUT/candidate.lean"
compile_one(){ local stem=$1 max=$2 src="PrimalitySheafVerification/${1}.lean" o=".lake/build/lib/lean/PrimalitySheafVerification/${1}.olean" i=".lake/build/lib/lean/PrimalitySheafVerification/${1}.ilean"; rm -f "$o" "$i"; lake env lean -DmaxErrors="$max" -DwarningAsError=false -o "$o" -i "$i" "$src" > "$OUT/${stem}.log" 2>&1; local rc=$?; printf '%s' "$rc" > "$OUT/${stem}.exit"; test "$rc" -eq 0 && test -s "$o" && test -s "$i"; }
set +e; compile_one Mock2 20; a=$?; compile_one Mock2_Advanced 20; b=$?; c=125; if test "$a" -eq 0 && test "$b" -eq 0; then compile_one Mock2_FunctionalAnalysis 20; c=$?; else echo blocked > "$OUT/Mock2_FunctionalAnalysis.log"; printf '%s' "$c" > "$OUT/Mock2_FunctionalAnalysis.exit"; fi; set -e; export RC_M2=$a RC_M2A=$b RC_FA=$c
python3 - <<'PY'
from pathlib import Path
import hashlib,json,os,re,subprocess,sys
sys.path.insert(0,str(Path('scripts').resolve())); import fa422_canonical_decl_tournament as E
v=os.environ['VARIANT']; o=Path(os.environ['OUT']); p=Path('PrimalitySheafVerification/Mock2_FunctionalAnalysis.lean'); x=p.read_text(); y=subprocess.check_output(['git','show','HEAD:PrimalitySheafVerification/Mock2_FunctionalAnalysis.lean'],text=True); bh=hashlib.sha256(y.encode()).hexdigest(); ch=hashlib.sha256(x.encode()).hexdigest(); log=(o/'Mock2_FunctionalAnalysis.log').read_text(errors='replace'); ms=list(re.finditer(r'Mock2_FunctionalAnalysis\.lean:(\d+):(\d+):\s+(?:error(?:\([^)]*\))?:|error:)',log)); f=int(ms[0].group(1)) if ms else None; col=int(ms[0].group(2)) if ms else None; a=int(os.environ['RC_M2']); b=int(os.environ['RC_M2A']); c=int(os.environ['RC_FA']); idx=E.decl_index_at(x,f); bi=2658; better=c==0 or (isinstance(f,int) and f>31726 and isinstance(idx,int) and (idx>bi or (idx==bi and len(x.splitlines())==len(y.splitlines())))); stmt=E.manifest(x)==E.manifest(y); imp=E.core.imports(x)==E.core.imports(y); bad=E.core.forbidden_hits(x); ok=bh=='71dc36f16ebea92d537aa40a5d420443e4bcb93ccb76fea31efb40a6cb5c3aa0' and a==0 and b==0 and better and stmt and imp and not any(bad.values()); s={'classification':'VERIFIED' if ok else 'CANDIDATE_REJECTED','variant':v,'baseline_sha256':bh,'candidate_sha256':ch,'baseline_line_count':len(y.splitlines()),'candidate_line_count':len(x.splitlines()),'Mock2_exit':a,'Mock2_Advanced_exit':b,'FA_exit':c,'FA_error_headers_captured':len(ms),'FA_first_actual_error_line':f,'FA_first_actual_error_col':col,'FA_error_declaration_index':idx,'baseline_declaration_index':bi,'maxErrors_cap':20,'strictly_better':better,'authorized_for_materialization':ok,'statement_manifest_unchanged':stmt,'imports_unchanged':imp,'forbidden_token_audit':bad}; (o/'CURRENT.json').write_text(json.dumps(s,indent=2)+'\n'); (o/'CURRENT.txt').write_text('\n'.join(f'{k}={v}' for k,v in s.items())+'\n'); (o/('AUTHORIZED' if ok else 'REJECTED')).touch(); (o/'FINAL_EXIT').write_text('0' if ok else '1'); print(json.dumps(s,indent=2))
PY
